"""rename_password

Revision ID: 0a4b3a6eb149
Revises: 07c71f4389b6
Create Date: 2023-04-05 17:00:46.766553

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0a4b3a6eb149"
down_revision = "07c71f4389b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dog_model",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "user_model",
        "email",
        existing_type=sa.VARCHAR(length=254),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    op.drop_index("ix_user_model_email", table_name="user_model")
    op.create_unique_constraint(None, "user_model", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_model", type_="unique")
    op.create_index("ix_user_model_email", "user_model", ["email"], unique=False)
    op.alter_column(
        "user_model",
        "email",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=254),
        existing_nullable=False,
    )
    op.drop_table("dog_model")
    # ### end Alembic commands ###
